### ISSUE TITLE
Unable to pass Github test 

### ISSUE THREAD

**Issue by RobinHYuan** [SiEPIC/openEBL-2024-10#12]
My design(Attached ->[EBeam_robin_h_y.zip](https://github.com/user-attachments/files/17182170/EBeam_robin_h_y.zip)) has passed the functional verification and Klayout DRC-Ebeam tests. However, it cannot pass the Github merge and verification tests. 
![image](https://github.com/user-attachments/assets/98a185fa-c3aa-4078-be2e-1cb89e1b8a43)
![image](https://github.com/user-attachments/assets/4e51f41d-a62c-4b7b-ac3c-dcae57a56fd5)
![image](https://github.com/user-attachments/assets/5dac6a48-8505-4c97-9517-06b0a0b402ca)

**Comment by janineboerner** [comment]
I have a similar situation with Layout Verifictaion and Merge.
![upload_error](https://github.com/user-attachments/assets/778be357-0333-401a-9fc0-e1cc40c4aa76)

**Comment by giamoug** [comment]
I have the same issue. Although it passes the verification test it cannot pass the github merge

**Comment by LenaSchad** [comment]
the problem affects me too. Is there a solution for it. Thanks for any advice!

**Comment by LiliaCN** [comment]
Same for me. Passed in KLayout, but not in github.

**Comment by lukasc-ubc** [comment]
I fixed it today.  So after you make changes to your pull request, the auto check should run, and work!
Please let me know if it is ok.

**Comment by RobinHYuan** [comment]
Hi professor. I think the fix worked. My design passed the GitHub CI test. Thanks!

**Comment by RobinHYuan** [comment]
Hi professor. My design now passes the merge test but still fails the verification test.

**Comment by mghazialsharif** [comment]
> Hi professor. My design now passes the merge test but still fails the verification test. ![image](https://private-user-images.githubusercontent.com/68177491/372677943-80df0fd5-ff50-47e4-9b06-f43efa2e423f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Mjc1ODAsIm5iZiI6MTcyNzgyNzI4MCwicGF0aCI6Ii82ODE3NzQ5MS8zNzI2Nzc5NDMtODBkZjBmZDUtZmY1MC00N2U0LTliMDYtZjQzZWZhMmU0MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAwMDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MGZkMzFjZDY3ZWY2ZTM2ZGU4YTU4MTI3YjA2NjYwNDQzNzM5ZGU3NDVjMmM5ZjU2NWE0YTlhYTZjMzI3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-F9aKKsezaSaxnuzaIAE-OoyqMCFIo0bmPdAH_sdGkE)

I have the same error is anybody know how we can fix it?

**Comment by AjayKrish95** [comment]
Hello Professor, 

Running into a similar issue as Robin. KLayout verification passes with no errors. 

![Verification Error Message](https://github.com/user-attachments/assets/d4a794f7-6ee4-46ab-96f5-9198c1fd45d3)

**Comment by aedanmcf** [comment]
I am also having the same verification error as the others

**Comment by ArminTabesh** [comment]
I'm facing the layout verification error, too. The verification test on KLayout is successful, but Github doesn't accept it. I tried four times, and each time, I changed something in the GDS file that I thought might be the problem, but it just doesn't work.

**Comment by RobinHYuan** [comment]
FYI, i had some problems with my floor plan.

**Comment by Elecman61** [comment]
I am receiving an error of GC pitch should be minimum 60 um. I checked and I don't see any issue. Not sure what it is.

**Comment by mghazialsharif** [comment]
> FYI, i had some problems with my floor plan. Now my design has passed the tests.
> 
> edit: nvm, still failing the test

Could you please let us know what was the problem? with the floor plan and how you solved it?

**Comment by ejonkerUBC** [comment]
This continues to be an issue for me as well..
